apiVersion: v1
kind: Pod
spec:
  securityContext:
    runAsUser: 1000
  containers:
  - name: terraform
    image: hashicorp/terraform
    command:
    - cat
    tty: true
  - name: tfsec
    image: tfsec/tfsec-ci
    command:
    - cat
    tty: true
  - name: tflint
    image: ghcr.io/terraform-linters/tflint
    command:
    - cat
    tty: true
